sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t metbet/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true metbet/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker
  env: Docker-env
  bucket_name: elasticbeanstalk-us-east-2-385475616242
  on:
    all_branches: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
